/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CadastroFazenda: typeof import('./components/CadastroFazenda.vue')['default']
    CadastroResultado: typeof import('./components/CadastroResultado.vue')['default']
    CadastroTalhao: typeof import('./components/CadastroTalhao.vue')['default']
    CadastroUsuario: typeof import('./components/CadastroUsuario.vue')['default']
    EditarResultado: typeof import('./components/EditarResultado.vue')['default']
    EditToolbar: typeof import('./components/EditToolbar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ListagemFazendas: typeof import('./components/ListagemFazendas.vue')['default']
    ListagemTalhoes: typeof import('./components/ListagemTalhoes.vue')['default']
    ListagemUsuarios: typeof import('./components/ListagemUsuarios.vue')['default']
    ModalEdicaoFazenda: typeof import('./components/ModalEdicaoFazenda.vue')['default']
    ModalEdicaoUsuario: typeof import('./components/ModalEdicaoUsuario.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerravisionMap: typeof import('./components/TerravisionMap.vue')['default']
    TerravisionMapEdit: typeof import('./components/TerravisionMapEdit.vue')['default']
    TerravisionMapPreview: typeof import('./components/TerravisionMapPreview.vue')['default']
  }
}
