/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CadastroFazenda: typeof import('./components/CadastroFazenda.vue')['default']
    CadastroTalhao: typeof import('./components/CadastroTalhao.vue')['default']
    CadastroUsuario: typeof import('./components/CadastroUsuario.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ListagemFazendas: typeof import('./components/ListagemFazendas.vue')['default']
    ListagemTalhoes: typeof import('./components/ListagemTalhoes.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    ModalEdicaoFazenda: typeof import('./components/ModalEdicaoFazenda.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TerravisionMap: typeof import('./components/TerravisionMap.vue')['default']
    TerravisionMapPreview: typeof import('./components/TerravisionMapPreview.vue')['default']
  }
}
