/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/fazenda/': RouteRecordInfo<'/fazenda/', '/fazenda', Record<never, never>, Record<never, never>>,
    '/fazenda/cadastro': RouteRecordInfo<'/fazenda/cadastro', '/fazenda/cadastro', Record<never, never>, Record<never, never>>,
    '/fazenda/edicao': RouteRecordInfo<'/fazenda/edicao', '/fazenda/edicao', Record<never, never>, Record<never, never>>,
    '/missao/qa': RouteRecordInfo<'/missao/qa', '/missao/qa', Record<never, never>, Record<never, never>>,
    '/talhao/': RouteRecordInfo<'/talhao/', '/talhao', Record<never, never>, Record<never, never>>,
    '/talhao/cadastro': RouteRecordInfo<'/talhao/cadastro', '/talhao/cadastro', Record<never, never>, Record<never, never>>,
  }
}
